apiVersion: apps/v1
kind: Deployment
metadata:
  name: alcor
  labels:
    app: alcor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alcor
  template:
    metadata:
      labels:
        app: alcor
    spec:
      containers:
        - name: alcor
          image: ${ControllerImage}:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
