apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignite-cluster
spec:
  selector:
    matchLabels:
      app: ignite
  replicas: 3
  template:
    metadata:
      labels:
        app: ignite
    spec:
      serviceAccountName: ignite
      containers:
      - name: ignite-node
        image: apacheignite/ignite:2.10.0
        env:
        - name: OPTION_LIBS
          value: ignite-kubernetes
        - name: CONFIG_URI
          value: /opt/ignite/config/ignite-config.xml
        ports:
        - containerPort: 11211 # REST port number.
        - containerPort: 47100 # communication SPI port number.
        - containerPort: 47500 # discovery SPI port number.
        - containerPort: 49112 # JMX port number.
        - containerPort: 10800 # SQL port number.
        - containerPort: 10900 # Thin clients port number.
        volumeMounts:
        - name: ignite-config-volume
          mountPath: /opt/ignite/config
      volumes:
        - name: ignite-config-volume
          configMap: 
            name: ignite-config

