kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ignite-alcor-mac
roleRef:
  kind: ClusterRole
  name: ignite-alcor-mac
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ignite-alcor-mac
    namespace: ignite-alcor-mac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ignite-alcor-mac
  namespace: ignite-alcor-mac
rules:
  - apiGroups:
      - ""
    resources: # Here are resources you can access
      - pods
      - endpoints
    verbs: # That is what you can do with them
      - get
      - list
      - watch
---
apiVersion: v1
kind: Namespace
metadata:
  name: ignite-alcor-mac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ignite-alcor-mac
  namespace: ignite-alcor-mac
---
apiVersion: v1
kind: Service
metadata:
  # The name must be equal to TcpDiscoveryKubernetesIpFinder.serviceName
  name: ignite-alcor-mac-service
  # The name must be equal to TcpDiscoveryKubernetesIpFinder.namespaceName
  namespace: ignite-alcor-mac
  labels:
    app: ignite-alcor-mac
spec:
  type: LoadBalancer
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
    - name: sql
      port: 10803
      targetPort: 10800
    - name: thinclients
      port: 10900
      targetPort: 10900
  selector:
    app: ignite-alcor-mac
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ignite-alcor-mac
  name: ignite-alcor-mac
  namespace: ignite-alcor-mac
spec:
  selector:
    matchLabels:
      app: ignite-alcor-mac
  serviceName: ignite-alcor-mac-service
  replicas: 3
  template:
    metadata:
      labels:
        app: ignite-alcor-mac
    spec:
      serviceAccountName: ignite-alcor-mac
      containers:
        - name: ignite-alcor-mac-node
          image: ignite_alcor:lib8
          imagePullPolicy: IfNotPresent
          #resources:
            #requests:
              #cpu: "16"
          env:
            - name: OPTION_LIBS
              value: ignite-kubernetes,ignite-rest-http
            - name: CONFIG_URI
              value: https://raw.githubusercontent.com/futurewei-cloud/alcor/master/kubernetes/db/ignite/ignite_mac_config.xml
            - name: IGNITE_QUIET
              value: "false"
            - name: JVM_OPTS
              value: "-Djava.net.preferIPv4Stack=true"
            #- name: JVM_OPTS
              #value: "-Djava.net.preferIPv4Stack=true
                      #-server 
                      #-Xms20g
                      #-Xmx20g
                      #-XX:+AlwaysPreTouch
                      #-XX:+UseG1GC
                      #-XX:+ScavengeBeforeFullGC
                      #-XX:+DisableExplicitGC"
          ports:
            - name: port8080
              containerPort: 8080
            - name: port11211
              containerPort: 11211 # REST port number.
            - name: port47100
              containerPort: 47100 # communication SPI port number.
            - name: port47500
              containerPort: 47500 # discovery SPI port number.
            - name: port49112
              containerPort: 49112 # JMX port number.
            - name: port10800
              containerPort: 10800 # SQL port number.
            - name: port10900
              containerPort: 10900 # Thin clients port number.
          volumeMounts:
            - name: ignite-alcor-mac-config-volume
              mountPath: /opt/mac
      volumes:
        - name: ignite-alcor-mac-config-volume
          hostPath: 
            path: /root/work/mac
