kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ignite-alcor-port
roleRef:
  kind: ClusterRole
  name: ignite-alcor-port
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ignite-alcor-port
    namespace: ignite-alcor-port
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ignite-alcor-port
  namespace: ignite-alcor-port
rules:
  - apiGroups:
      - ""
    resources: # Here are resources you can access
      - pods
      - endpoints
    verbs: # That is what you can do with them
      - get
      - list
      - watch
---
apiVersion: v1
kind: Namespace
metadata:
  name: ignite-alcor-port
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ignite-alcor-port
  namespace: ignite-alcor-port
---
apiVersion: v1
kind: Service
metadata:
  # The name must be equal to TcpDiscoveryKubernetesIpFinder.serviceName
  name: ignite-alcor-port-service
  # The name must be equal to TcpDiscoveryKubernetesIpFinder.namespaceName
  namespace: ignite-alcor-port
  labels:
    app: ignite-alcor-port
spec:
  #type: LoadBalancer
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
    - name: sql
      port: 10802
      targetPort: 10800
    #- name: thinclients
      #port: 10900
      #targetPort: 10900
  selector:
    app: ignite-alcor-port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ignite-alcor-port
  name: ignite-alcor-port
  namespace: ignite-alcor-port
spec:
  selector:
    matchLabels:
      app: ignite-alcor-port
  serviceName: ignite-alcor-port-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ignite-alcor-port
    spec:
      serviceAccountName: ignite-alcor-port
      containers:
        - name: ignite-alcor-port-node
          image: ignite_alcor:lib8
          imagePullPolicy: IfNotPresent
          env:
            - name: OPTION_LIBS
              value: ignite-kubernetes,ignite-rest-http
            - name: CONFIG_URI
              value: https://raw.githubusercontent.com/kevin-zhonghao/alcor/xml/kubernetes/services/ignite_port_config.xml
            #- name: IGNITE_QUIET
              #value: "false"
            #- name: JVM_OPTS
              #value: "-Djava.net.preferIPv4Stack=true \
                      #-XX:+PrintGCDetails \
                      #-XX:+PrintGCTimeStamps \
                      #-XX:+PrintGCDateStamps \
                      #-XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 \
                      #-XX:GCLogFileSize=100M \
                      #-Xloggc:/opt/ignite/apache-ignite/work/log/ignite-gc.log \
                      #-server \ 
                      #-Xms50g \
                      #-Xmx50g \
                      #-XX:+AlwaysPreTouch \
                      #-XX:+UseG1GC \
                      #-XX:+ScavengeBeforeFullGC \
                      #-XX:+DisableExplicitGC"
          ports:
            - name: port8080
              containerPort: 8080
            - name: port11211
              containerPort: 11211 # REST port number.
            - name: port47100
              containerPort: 47100 # communication SPI port number.
            - name: port47500
              containerPort: 47500 # discovery SPI port number.
            - name: port49112
              containerPort: 49112 # JMX port number.
            - name: port10800
              containerPort: 10800 # SQL port number.
            - name: port10900
              containerPort: 10900 # Thin clients port number.
          volumeMounts:
            - name: ignite-alcor-port-config-volume
              mountPath: /opt/port
      volumes:
        - name: ignite-alcor-port-config-volume
          hostPath: 
            path: /root/work/port
