apiVersion: v1
kind: ConfigMap
metadata:
  name: route-configmap
data:
  application.properties: |
    microservices.vpc.service.url=http://vpcmanager-service.default.svc.cluster.local:9001
    microservices.subnet.service.url=http://subnetmanager-service.default.svc.cluster.local:9002
    microservices.dpm.service.url=http://dataplanemanager-service.default.svc.cluster.local:9010
    microservices.port.service.url=http://portmanager-service.default.svc.cluster.local:9006
    ignite.thin.client.enable=true
    ignite.host=ignite-alcor-service.ignite-alcor.svc.cluster.local
    ignite.port=10800
    logging.level.root=DEBUG
    logging.level.org.springframework.web=info
    logging.file.path=.
    logging.type=file
    management.health.redis.enabled=false

    opentracing.jaeger.udp-sender.host=10.111.132.59
    opentracing.jaeger.udp-sender.port=6831
    opentracing.jaeger.const-sampler.decision=true
    opentracing.jaeger.enabled=true
    opentracing.jaeger.log-spans=true
    opentracing.jaeger.enable-w3c-propagation=true
    opentracing.jaeger.enable-b3-propagation=true
    opentracing.jaeger.service-name=alcor-route
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: routemanager
  name: routemanager
spec:
  selector:
    matchLabels:
      app: routemanager
  replicas: 5
  template:
    metadata:
      labels:
        app: routemanager
    spec:
      volumes:
        - name: route-volume
          configMap:
            name: route-configmap
            items:
              - key: application.properties
                path: application.properties
      containers:
        - image: route_manager:v1.0
        #- image: fwnetworking/controller:route_manager-v0.3.0
          name: routemanager-web
          imagePullPolicy: IfNotPresent
          command: ["java", "-jar", "/app/AlcorRouteManager-0.1.0.jar", "--spring.config.location=/etc/app/application.properties"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: route-volume
              mountPath: /etc/app
          envFrom:
            - configMapRef:
                name: route-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: routemanager-service
  labels:
    name: routemanager-service
spec:
  type: NodePort
  ports:
    - port: 9003
      targetPort: 8080
      nodePort: 30003
  selector:
    app: routemanager
