apiVersion: v1
kind: ConfigMap
metadata:
  name: subnet-configmap
data:
  application.properties: |
    ignite.thin.client.enable=true
    ignite.host=ignite-alcor-service.ignite-alcor.svc.cluster.local
    ignite.port=10800
    logging.level.root=DEBUG
    logging.level.org.springframework.web=info
    logging.file.path=.
    logging.type=file
    apache.kafka.address=172.17.0.1:9092
    microservices.vpc.service.url=http://vpcmanager-service.default.svc.cluster.local:9001/project/
    microservices.mac.service.url=http://macmanager-service.default.svc.cluster.local:9005/macs
    microservices.route.service.url=http://routemanager-service.default.svc.cluster.local:9003/
    microservices.ip.service.url=http://ipmanager-service.default.svc.cluster.local:9004/ips/
    microservices.port.service.url=http://portmanager-service.default.svc.cluster.local:9006/

    rbac.policy.type=Enforced
    management.health.redis.enabled=false

    opentracing.jaeger.udp-sender.host=10.111.132.59
    opentracing.jaeger.udp-sender.port=6831
    opentracing.jaeger.const-sampler.decision=true
    opentracing.jaeger.enabled=true
    opentracing.jaeger.log-spans=true
    opentracing.jaeger.enable-w3c-propagation=true
    opentracing.jaeger.enable-b3-propagation=true
    opentracing.jaeger.service-name=alcor-subnet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: subnetmanager
  name: subnetmanager
spec:
  selector:
    matchLabels:
      app: subnetmanager
  replicas: 5
  template:
    metadata:
      labels:
        app: subnetmanager
    spec:
      volumes:
        - name: subnet-volume
          configMap:
            name: subnet-configmap
            items:
              - key: application.properties
                path: application.properties
      containers:
        - image: subnet_manager:v1.0
        #- image: fwnetworking/controller:subnet_manager-v0.3.0
          name: subnetmanager-web
          imagePullPolicy: IfNotPresent
          command: ["java", "-jar", "/app/AlcorSubnetManager-0.1.0.jar", "--spring.config.location=/etc/subnet/application.properties"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: subnet-volume
              mountPath: /etc/subnet
          envFrom:
            - configMapRef:
                name: subnet-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: subnetmanager-service
  labels:
    name: subnetmanager-service
spec:
  type: NodePort
  ports:
    - port: 9002
      targetPort: 8080
      nodePort: 30002
  selector:
    app: subnetmanager

